In [ ]:
document_corpus = ["this is good phone phone" , 
                   "this is bad mobile mobile" , 
                   "she is good good cat" , 
                   "he has bad temper temper" , 
                   "this mobile phone phone is not good good"
                  ]


In [ ]:
import pandas as pd
import nltk
nltk.download('punkt')


from nltk.tokenize import word_tokenize
i=0
while i<len(document_corpus):
 print(word_tokenize(document_corpus[i]))
 i+=1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
['this', 'is', 'good', 'phone', 'phone']
['this', 'is', 'bad', 'mobile', 'mobile']
['she', 'is', 'good', 'good', 'cat']
['he', 'has', 'bad', 'temper', 'temper']
['this', 'mobile', 'phone', 'phone', 'is', 'not', 'good', 'good']


In [ ]:
pop=[]
i=0
while i<len(document_corpus):
 pop.append(word_tokenize(document_corpus[i]))
 i+=1
print('Token Population')
print(pop)

Token Population
[['this', 'is', 'good', 'phone', 'phone'], ['this', 'is', 'bad', 'mobile', 'mobile'], ['she', 'is', 'good', 'good', 'cat'], ['he', 'has', 'bad', 'temper', 'temper'], ['this', 'mobile', 'phone', 'phone', 'is', 'not', 'good', 'good']]


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

stops = set(stopwords.words('english'))
print(stops)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
{'once', 're', 'weren', 've', 'hasn', 'for', 'whom', 'are', 'until', "hasn't", 'such', 'over', 'ma', 'was', 'each', 't', 'down', 'after', 'who', 'being', 'mustn', 'into', 'did', 'he', 'has', 'what', 'while', "wouldn't", 'our', "couldn't", 'them', 'where', 'too', 'ain', 'doesn', 'been', 'yours', 'your', 'does', "you're", 'am', 'themselves', 'further', 'hadn', 'ourselves', "mustn't", 'below', "that'll", 'or', 'couldn', 'some', 'at', "you'd", 'those', 'she', 'the', 'will', "weren't", 'than', 'be', 'only', 'both', 'out', 'it', 'all', 'just', "won't", 'can', 'having', 'd', 'i', 'any', 'shan', 'herself', 'now', "mightn't", 'that', 'have', 'not', "hadn't", 'doing', 'as', 'its', 'their', "you've", 'him', 'during', 'me', 'we', 'to', 'in', 'under', "you'll", 'nor', "didn't", 'why', 'll', 'which', 'yourself', 'how', 'mightn', "it's", 'same', "isn't", 'myself', 'no', 'yourselves', "aren't

In [ ]:
from nltk.corpus import stopwords
stops = set(stopwords.words('english'))
i=0
bow=[]

#Add elements
while i<len(pop):
  for word in pop[i]: 
    if word not in stops:
      bow.append(word)
  i+=1
print(bow)

#Remove commas,full stops...
for x in bow:
  if not x.isalpha():
    bow.remove(x)

#unique the list
t=set(bow)
bow=list(t)

print("Final Processed Bag of words:")
print(bow)

# print('Length:',len(bow))


['good', 'phone', 'phone', 'bad', 'mobile', 'mobile', 'good', 'good', 'cat', 'bad', 'temper', 'temper', 'mobile', 'phone', 'phone', 'good', 'good']
Final Processed Bag of words:
['phone', 'bad', 'cat', 'good', 'mobile', 'temper']


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
Vec = vectorizer.fit_transform(document_corpus)

print(Vec)

  (0, 11)	1
  (0, 5)	1
  (0, 2)	1
  (0, 8)	2
  (1, 11)	1
  (1, 5)	1
  (1, 0)	1
  (1, 6)	2
  (2, 5)	1
  (2, 2)	2
  (2, 9)	1
  (2, 1)	1
  (3, 0)	1
  (3, 4)	1
  (3, 3)	1
  (3, 10)	2
  (4, 11)	1
  (4, 5)	1
  (4, 2)	2
  (4, 8)	2
  (4, 6)	1
  (4, 7)	1


In [ ]:
# Extra code testing


import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.preprocessing.sequence import pad_sequences



token_docs = [doc.split() for doc in document_corpus]
all_tokens = set([word for sentence in token_docs for word in sentence])
word_to_idx = {token:idx+1 for idx, token in enumerate(all_tokens)}

X = np.array([[word_to_idx[token] for token in token_doc] for token_doc in token_docs], dtype=object)

X_padded = pad_sequences(X, padding="post")

X_df = pd.DataFrame(X_padded) 

print(X_df)

   0   1  2   3   4   5  6  7
0  9  12  7   1   1   0  0  0
1  9  12  2   8   8   0  0  0
2  3  12  7   7   4   0  0  0
3  5   6  2  11  11   0  0  0
4  9   8  1   1  12  10  7  7


In [ ]:
data_corpus = set()
for row in document_corpus:
    for word in row.split(" "):
        if word not in data_corpus:
            data_corpus.add(word)

data_corpus=sorted(data_corpus)

print(data_corpus)

['bad', 'cat', 'good', 'has', 'he', 'is', 'mobile', 'not', 'phone', 'she', 'temper', 'this']


In [ ]:
length = len(max(document_corpus, key = len).split(" "))
print(length)

8


In [ ]:
index_based_encoding=[]
for row in document_corpus:
    row_encoding = []
    split = row.split(" ")
    for i in range(length):
        if i <= len(split)-1:
            row_encoding.append(data_corpus.index(split[i])+1)
        else:
            row_encoding.append(0)
    index_based_encoding.append(row_encoding)

print(index_based_encoding)

[[12, 6, 3, 9, 9, 0, 0, 0], [12, 6, 1, 7, 7, 0, 0, 0], [10, 6, 3, 3, 2, 0, 0, 0], [5, 4, 1, 11, 11, 0, 0, 0], [12, 7, 9, 9, 6, 8, 3, 3]]


In [ ]:
arr1 = []
for row in document_corpus:
    row_encoding = []
    split = row.split(" ")
    for word in data_corpus:
        if word in split:
            row_encoding.append(1)
        else:
            row_encoding.append(0)
    arr1.append(row_encoding)

print(arr1)


arr2 = []
for row in document_corpus:
    row_encoding = []
    split = row.split(" ")
    for word in data_corpus:
        count = split.count(word)
        if word in split:
            row_encoding.append(count)
        else:
            row_encoding.append(count)
    arr2.append(row_encoding)

print(arr2)

[[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], [0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1]]
[[0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1], [1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1], [0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0], [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0], [0, 0, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1]]


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(document_corpus)
print(vectorizer.get_feature_names())


print(X.toarray())

['bad', 'cat', 'good', 'has', 'he', 'is', 'mobile', 'not', 'phone', 'she', 'temper', 'this']
[[0 0 1 0 0 1 0 0 2 0 0 1]
 [1 0 0 0 0 1 2 0 0 0 0 1]
 [0 1 2 0 0 1 0 0 0 1 0 0]
 [1 0 0 1 1 0 0 0 0 0 2 0]
 [0 0 2 0 0 1 1 1 2 0 0 1]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(document_corpus)
print(vectorizer.get_feature_names())


print(X.toarray())

['bad', 'cat', 'good', 'has', 'he', 'is', 'mobile', 'not', 'phone', 'she', 'temper', 'this']
[[0.         0.         0.34273991 0.         0.         0.28832362
  0.         0.         0.82578944 0.         0.         0.34273991]
 [0.4023674  0.         0.         0.         0.         0.28097242
  0.80473481 0.         0.         0.         0.         0.33400129]
 [0.         0.49317635 0.6605719  0.         0.         0.27784695
  0.         0.         0.         0.49317635 0.         0.        ]
 [0.31283963 0.         0.         0.38775666 0.38775666 0.
  0.         0.         0.         0.         0.77551332 0.        ]
 [0.         0.         0.51309679 0.         0.         0.2158166
  0.30906082 0.38307292 0.61812163 0.         0.         0.2565484 ]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
